name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: s4sheikh
          password: ${{ secrets.DOCKER_TOKEN }}
        env:
          CICDSECRET3ENV: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t s4sheikh/devops-cicd-app1 .

      - name: Push Docker image
        run: docker push s4sheikh/devops-cicd-app1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull s4sheikh/devops-cicd-app1
            docker stop app || true
            docker rm app || true
            docker run -d -p 80:3000 --name app s4sheikh/devops-cicd-app1
